### ISSUE TITLE
hint for correct phone number format

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#105]
adding phone number on creating a new user might get confusing as there is no hint on the required format. If user enters just the phone number part without the country code the error "moible phone is invalid" is returned but there is nothing that says what exaclty is the cause or what should the correct phone number look like. 

Ideally there should be some hint in the UI that would help user to use the correct format to begin with. Also error message should indicate the what is the correct format.

**Comment by maciej-szlosarczyk** [comment]
Fixed with a placeholder value:

![Screenshot 2019-03-18 at 16 34 47](https://user-images.githubusercontent.com/2331765/54537841-e14a1d00-499b-11e9-8522-2abe0ad6e0c4.png)
