### ISSUE TITLE
Interface corrections

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#120]
Domain list view will be available on the web page:
short list in index: https://eis-dev.voog.com/
and full list on separate page: https://eis-dev.voog.com/domeenid/domeenioksjonid

so the blue domain list view of the auction center should be moved behind login barrier and painted green (should be the index page opened after logging in). https://auction.infra.tld.ee/auctions

From the full list view on the EIS web page will point directly to bidding view /uid/offers/new

**Comment by maciej-szlosarczyk** [comment]
Adding a sign-in requirement for auctions' list is complex, since JSON list is served from the same action. It also will break both staging and registrar test environments, as we have no staging website with that.

Colors are changed in #122

**Comment by vohmar** [comment]
need to color also the main menu+tips area

![image](https://user-images.githubusercontent.com/7734747/54741402-02db1c80-4bc7-11e9-857a-0a0620e09896.png)

a bit offtopic, but the footer also need content - should be the sama as on public website:
https://www.internet.ee/

**Comment by maciej-szlosarczyk** [comment]
I'll try to do it, but where does this come from? The PHP prototype from https://github.com/internetee/auction_css has this in blue:

![Screenshot 2019-03-21 at 12 19 15](https://user-images.githubusercontent.com/2331765/54745960-a2061100-4bd3-11e9-8b61-18a320e30f2c.png)

**Comment by maciej-szlosarczyk** [comment]
The green feature banner is now in master.

**Comment by maciej-szlosarczyk** [comment]
@vohmar Additional footer links and changes to the top bar are in master and on staging.

**Comment by vohmar** [comment]
Some more improvements are necessary:

1. There should be also "Avalik portaal / Public Portal / Oбщественный портал" tab as the first option next to the "Oksjonikeskkond / Auction Portal" tab (internet.ee)
1.1 While at it please rename "Oksjoniportaal" to "Oksjonikeskkond"
2. On the domain list view rename the name of the page from Okjonid to Domeenioksjonid
3. Corrections on the green tips section:
3.1 add comma to the end of Esita pakkumus and replace following text with the one from internet.ee: "mida saad muuta ja tühistada oksjoni lõppemiseni. Domeenioksjonid toimuvad pimeoksjoni stiilis, mis tähendab, et keegi teine esitatud pakkumise suurust ei näe."
3.2 replace the text in second point with this: et: "Anname oksjonitulemustest teada ka e-posti teel. Loodetavasti on sinu pakkumine kõrgeim ja saad õiguse soovitud domeeninime registreerimiseks."; en: "We will let you know about the result by email. Hopefully your offer was the highest and you will get the reservation to register the domainname."
3.3 laste sentance pointing to the user agreement: Replace Loe lisaks meie tingimused leheküljelt. with et: "Tutvu ka oksjonikeskkonna kasutajatingimustega (link: https://www.internet.ee/domeenid/domeenide-oksjonikeskkonna-kasutajatingimused) ja loe detailsemalt oksjoniprotsessist."; en: "Please check out the terms and conditions (link: https://www.internet.ee/domains/auction-environment-user-agreement) of .ee auctioning process."
4. Sign in view
4.1 Replace the term "Logi sisse" with "Sisene"
4.2 Replace the text in the "logi sisse isikut tõendava dokumendiga" section: et: "Sisene kasutades Eesti (sh e-residendi) ID kaarti, mobiil IDd, pangalinki või EU liikmeriikide elektroonset isikutunnistust (EIDAS)" en: "Sing in using Estonian (incl e-residents) ID card, mobile ID, Bank link or other EU citizen's electornic ID supported by EIDAS"
5. in Create new account view (incl electronic id's) replace the terms and conditions text: et: "Olen tutvunud ja nõustut domeenide oksjonikeskkonna kasutajatingimustega (link: https://www.internet.ee/domeenid/domeenide-oksjonikeskkonna-kasutajatingimused)"; en: "I have read and agree with auction portal user agreement (link: https://www.internet.ee/domains/auction-environment-user-agreement)"
6. Replace in the new and edit offer views (ie: https://auction.infra.tld.ee/auctions/3381b296-df9c-4059-96dc-f623b3b37f7e/offers/new) field heading Pakkumus: et "Domeeni registreerimise eelisõiguse pakkumus"; en "Offer for the reservation of the domain name"
7. In offer detail view (ie. https://auction.infra.tld.ee/offers/cb88e223-50ed-4533-b8b5-564a5d14d22c) there are auction rules below the offer details. Replace the text in the first blind auction section. et: "Enampakkumine toimub domeeninime reserveerimise õigusele. Oksjoni võitjal tuleb lisaks tasuda ka domeeni registreerimise tasu registripidajale vastavale valitud registripidaja teenuste hinnakirjale. Pakkumised on konfidentsiaalsed, osalejad ei näe, mitu pakkumust ja mis hinnaga on tehtud"; en "The bids are for domain name reservation. The winner will have to pay additional registration fee to the regsitrar according to their pricelist. Offers are confidential, participants do not see how many offers have been made and with what price."

**Comment by vohmar** [comment]
Some improvement requests for UI

From last list, it seems that nr 6 is missing

other things:
1. invoice list (https://auction.internet.ee/invoices): column heading  due date missing et translation.  Should be "Tähtaeg" 
![image](https://user-images.githubusercontent.com/7734747/54996496-2391e080-4fd2-11e9-86cd-7aa04dfda915.png)

2. message on session expiration partly not translated. 
![image](https://user-images.githubusercontent.com/7734747/54996485-1d036900-4fd2-11e9-9663-c773d37aab29.png)

3.1. Error message: captcha. Should be "reCaptcha kontroll ebaõnnestus. Palun proovige uuesti!" 
![image](https://user-images.githubusercontent.com/7734747/54996589-6358c800-4fd2-11e9-988e-55777697b3b9.png)
3.2. Error message:  kasutaja tingimused tuleb nõustuda asendada "Pead nõustuma domeenide oksjonikeskkonna kasutajatingimustega"

4. Menu Minu Pakkumused should be renamed to Minu pakkumised. Also on the same page (https://auction.internet.ee/offers)

5. Add domain name to the offer view. One idea would be to replace word "Domeeni" in the page heading with the domain name that the bid is being made for ie "x2.ee registreerimise eelisõiguse pakkumus" / "Offer for the reservatsion of x2.ee"

**Comment by maciej-szlosarczyk** [comment]
3.2 is impossible without reworking all errors in both languages. The required sentence structure is:

`[custom attribute name] [error message]`

So, for example:

```
[Terms and conditions], [must be accepted]
[Email], [must be blue and flowery]
[User], [cannot be a robot]
```

5: Would this work? The text is quite a mouthful, so adding a domain name there is not an option. We don't know if it is not very long.

![image](https://user-images.githubusercontent.com/2331765/55002947-1c71cf00-4fe0-11e9-9569-b971a7fc7e82.png)

The rest is fixed in #149.

**Comment by vohmar** [comment]
yes it is fine to put the domain name under the heading as you proposed

**Comment by vohmar** [comment]
some more imporvements requests:

1. The success message on making the bid should be more clear - It's currently just "Loodud". Replace this with "Pakkumus edukalt esitatud" 
![image](https://user-images.githubusercontent.com/7734747/55003167-89856480-4fe0-11e9-853a-1b7e0f7eaaa9.png)

2. Rename "registreeru enne" in results view  to "Registreeri hiljemalt" / "Registration deadline" 
![image](https://user-images.githubusercontent.com/7734747/55003869-d7e73300-4fe1-11e9-97af-441aad4f7f3b.png)

**Comment by vohmar** [comment]
all good
