### ISSUE TITLE
Admin: registration_term description is incorrect

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#122]
description for registration_term parameter says:

Number of days before the auctioned domain must be registered, starting from the auction start. Default: 14

while in reality the count starts from the time resgistration code was issued/released

**Comment by maciej-szlosarczyk** [comment]
Fixed in #124.

New description reveals an implementation detail, but we can probably live with that:

>   Number of days before the auctioned domain must be registered, starting from release of
>   registration code. When a result is created, the date is first inserted, and then prolonged
>   when registration code is released. Default: 14

If this is fine, I'll merge it right away @vohmar
