### ISSUE TITLE
Download invoice 

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#147]
/invoices

the invoice view is lacking few important elements like recipient info and issuer info (EIS).

Also the view is missing download invoice option and print button

**Comment by vohmar** [comment]
lets make the printed / downloaded invoice look similar to the attached one
[invoice-3008356.pdf](https://github.com/internetee/auction_center/files/3012083/invoice-3008356.pdf)

* on issuer details lets leave out issuer, payment term, description and ref nr
* client details should be filled with the data we get from billing profile
* and EIS's data in the footer should be somewhat identical

**Comment by vohmar** [comment]
need to reset the invoice number range as well. Accountig decided they do not like the short ones we have now and defined a range for us starting from 250000 and going up until 299000 initially (it is possible to widden the range when the time comes). So we should aslo renumber the invoices we have generated already.

**Comment by maciej-szlosarczyk** [comment]
Invoice numbers are a Postgres sequence, we can and probably should do it without code change/migration.

```sql
ALTER SEQUENCE public.invoices_number_seq RESTART WITH 250000;
UPDATE invoices set number = DEFAULT;
```

Calling @ratM1n and @teadur to give their opinion

**Comment by maciej-szlosarczyk** [comment]
This is fixed now, right? @vohmar

**Comment by vohmar** [comment]
in production
