### ISSUE TITLE
Captcha fails to load in production

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#150]
Captcha check on making the bid with non e-id account fails to load - key issue

![Screenshot from 2019-03-26 07-12-16](https://user-images.githubusercontent.com/7734747/54975044-8bc6cf00-4f9e-11e9-8982-ce2f9837a6fe.png)

**Comment by teadur** [comment]
v3 recaptcha key was used, that was not supported.
changed to v2 key and works now.
