### ISSUE TITLE
Error on password change

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#151]
Error returned when user changed their password - password change it self was successful

![image](https://user-images.githubusercontent.com/7734747/54996969-5a1c2b00-4fd3-11e9-9d58-6c0c499a2cf8.png)

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, how is this related to password change? We don't ask for reCAPTCHA on password change.

**Comment by vohmar** [comment]
to be honest I cannot remember how exaclty this error revealed itself, but testing the password change at the moment does not return any errors atm
