### ISSUE TITLE
Return from credit card payment causes an error

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/auction_center#154]
When user clicks "back" on EveryPay payment and does not complete the CC payment, there's a 500 error.

It should be a clean redirect.

**Comment by maciej-szlosarczyk** [comment]
@vohmar: need text to display to user on return from unsuccessful payment:

![Screenshot 2019-03-27 at 10 08 18](https://user-images.githubusercontent.com/2331765/55059695-4a0a5700-5078-11e9-8030-db2bea1a59e0.png)

It can be for an reason, from user clicking back to payment being in the wrong amount.

**Comment by vohmar** [comment]
"Makse ebaõnnestus!"
