### ISSUE TITLE
card payments fail

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#158]
> Olen arvet nr .. proovinud tasuda kahe erineva Swedbanki
> krediitkaardiga (Visa ja MasterCard) ning arvet nr .. LHV
> deebet-krediitkaardiga (MasterCard). Kõikidel juhtudel tuleb ette
> kaardiandmete sisestamise leht, kuid sellelt edasi minnes teatab
> every-pay.eu processor viivitamata "Sorry, payment was unsuccessful".
> Ei ilmu ka ootuspärast kaardi väljaandja panga "Secure Pay" lehte.

there is no sign of the payment in the everypay side.

**Comment by vohmar** [comment]
Response from everypay:

> Leidsime vea, mille pärast maksed ei lähe läbi.  Teil on 'amount' väljas  formaat vale, teil on kasutusel koma: "code": 2008,  "message": "The amount 'x,xx' is invalid" Tegelikult on õige kasutada punkti: x.xx

apparently they check this in production but not in test

**Comment by maciej-szlosarczyk** [comment]
Fixed in #159

**Comment by vohmar** [comment]
in prodcution
