### ISSUE TITLE
Admin: improve search

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#170]
* Invoice search is currently only possible using users email address.
Please include user name, billing profile name and domain name also in the search 

* billing profile is missing search
Please add option to search from user name and billing profile name

* user search is by email address
Please include the name in search as well

**Comment by vohmar** [comment]
* billing profile search searches only from the beginning of a string ie if profile name has two strings one cannot search by the second or third string (without adding % in front)
* invoice search by domain name nor billing profile name does not return results

**Comment by maciej-szlosarczyk** [comment]
Both errors should be fixed now.
