### ISSUE TITLE
Password chage instructions sent in Estonian

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#172]
the password change instructions are always sent in Estonian regardless of the interface language

**Comment by karlerikounapuu** [comment]
This is probably related to #359, as I'm not able to reproduce this bug in my development environment. I've got a feeling it has to do something with `cache_classes` setting in both production & staging environment, which results in mixing `en` and `et` translations.

**Comment by vohmar** [comment]
just retested this  - the problem is still there in current master. If you say that you are unable to repeat this on dev env then this indeed looks like the cache_classes bug.

**Comment by vohmar** [comment]
ok the password change instructions are sent in a language last set by the user in the UI - so it is not the current ui language in the reset password window but locale value in the users table. My bad should have remembered this. No issues here.
