### ISSUE TITLE
Admin: statistics

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#174]
Add view for statistics in admin interface

* number of auctions vs domains with and without bid - per day (graph)
* average number of bids per domain that had at least 1 bid - per day (graph)
* average number of bids - per day, per month, per year (graph)

* metric of paid but unregistered domains - count with configurable time gap (slider?)
* ratio of paid/updaid invoices (percentage) - graph
* ratio of registered/unregistered domains vs number of invoices (percentage) - graph
* ratio of registered/unregistered domains vs paid invoices (percentage) - graph

* auction winners - private vs organisations - bar chart with split bars indiationg ratio
* geography of auction winners (total)- map
* auction wins per user (total) - pie chart

**Comment by vohmar** [comment]
we use highcharts on homepage (https://www.internet.ee/help-and-info/statistics) to display graphs - just for consideration

**Comment by yulgolem** [comment]
> number of auctions vs domains with and without bid - per day (graph)
number of auctions created at this day or number of auctions active at this day? Same for the with/without - active at this day?

And at this day we would like to get 3 numbers - Auctions total, Auctions with bids, Auctions without bids, am I correct?

**Comment by vohmar** [comment]
that is correct - total number of auction per day and out of these number of auctions with at least one bid and number of auctions with no bids

**Comment by yulgolem** [comment]
>  metric of paid but unregistered domains - count with configurable time gap (slider?)

I suppose we need to calculate & store this metric every day at some time, because count of Results with status 'payment_received' will differ from day to day.

**Comment by vohmar** [comment]
what is meant here is count of scenarios where invoice was paid but the domain was not registered during the time that was given (currently 14 days) and domain went for another round of auction. There is a special status for such domains - Domain not registered. So there should not be a need for storing anything extra. Same goes for paid and unpaid invoices - we are looking for the end result of a single round of a domain auction here with these metrics.

**Comment by yulgolem** [comment]
Ah, so we are counting here results with 'domain_not_registered'. But if we are talking time gap (or date range), which results should we include in dataset? Results, which auctions was ended in this range? Or just with registration_due_date in range? Or we are not talking range now and would like to see a current snapshot?

**Comment by vohmar** [comment]
regarding domain not registered, Payment not received and no bids we would like to be able to spot the trends (i think this applies to all the metrics actually) and it would be good if user can zoom out on the graphs. For example domains not registered - these do not happen very often luckily, so to get a meaningful result one should zoom out from single day to week, month or year view for example and then look for trends from period to period

WIth invoices it seems logical to use invoice create date as basis. With bids, payments and registrations we should use auction date, i think... It would be also interesting to know the deadline to analyse how that affects the results. Not that clear here.

One more idea popped into mind - average number of days from auction to payment, from payment to registration and why not from auction to registration

**Comment by yulgolem** [comment]
OK, thanks, I think I got it.

**Comment by yulgolem** [comment]
> auction winners - private vs organisations - bar chart with split bars indiationg ratio
This metric is dropped out atm - have no clue how to differ.

**Comment by yulgolem** [comment]
> average number of bids - per day, per month, per year (graph)

We should think about visualisation here. In all other examples we've got one form to choose date range for all the graphs.
I suppose we cannot use such range here. Average number of bids per day is on previous graph, and per month/year... we should use separate graphs/requests for it, I suppose.

**Comment by vohmar** [comment]
OK run it on prod data and have some feedback:
* current solution could not handle the whole history - marked 1 year period to fetch and was stopped by timeout after I would guess 5 minutes of waiting. So it might be that we need to put the metrics in special table(s) and update with scheduled job like once a day
* shorter periods revealed that
  * auctions chart returns same value for each day
  * average number of bids per domain is constant 0
  * paid but unregistered domains is also 0
  * unpaid invoice percentage - seems to provide little value in its current form as it lacks the context of number of invoices (if there are only 2 invoices issued and one is not paid the result is 50% of failed payments that is scary on its own). Lets try to add number of issued invoices to the graph and use failed invoice count as second value instead of percentage
  * Registered & unregistered domains vs number of paid & unpaid invoices - the basis of this chart needs to be changed as I see that on some days there are more registered domains than invoices issued. We need to split this up into two separate charts 1) out of total issued invoices how many domains were registered and the rest is obviously unregistered 2) out of total paid invoices how many ended with registration and again rest were unregistered. Thinking about layered barchart here - bar length represents number of invoices issued or invoices paid respectively and the bar is split into two layers - registered and unregistered domains.

**Comment by vohmar** [comment]
Reviewed the stats as agreed focusing on date aggregation level, but had other thought as well:

- auctions - OK as is
- average nr of bids per domain - weekly steps
- NEW: registered domains vs auctions % - month (how many auctions ended with actual registration out of total auctions held)
- paid but unregistered domains - month
- unpaid invoices % - week
- Registered & unregistered domains vs number of paid & unpaid invoices
  - registered and unregistered vs paid - week (how many of the paid invoices were registered and unregistered - weekly view of paid but unregistered domains graph)
  - registered and unregistered vs unpaid - week (how many of the issued invoices were paid and how many were unpaid.)
- auction wins per user - ok
- auction wins by country - ok

PS: I am starting to think that we should consider some BI tool for this ie Pentaho to more easily allow dashboard building, graph fiddling aggregations etc. Lets get the ones described out to users (Jaana) lets hope it covers all the basic needs and I'll look into (open source) BI world to cover any extra requirements.

**Comment by yulgolem** [comment]
Will apply the changes.
Agreed with possibility of external BI usage. But maybe we should look for something more rails-specific like https://github.com/ankane/blazer ?

**Comment by vohmar** [comment]
looks almost good for now
* please change the formula of the second "Weekly average number of bids" graph to show average nr of bids for auctions with at least 1 bid ie there is 10 auctions out of which 3 get bids - 1. has 3 bids, 2. has 2 bids and 3. has 1 bid so the average for that wee is 2
