### ISSUE TITLE
Invoice: English item description

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#175]
The invoice item description references the registration code as transfer code - that is not correct as trasnfer code is specific term for code used for registrar transfer.

The term transfer code in the invoice item descriotion should be replaced with the term reservation code

PS: currently all invoices seem to be in Estonian. When is the english invoice generated?

**Comment by maciej-szlosarczyk** [comment]
There is no English invoice item description generated, not anymore. Item description comes from default locale, so in our case only Estonian.

Please provide replacements for the following texts:

```
Domain transfer code for %{domain_name} (auction %{auction_end})
Domeeni %{domain_name} (%{auction_end}) registreerimiskood
```

where auction_end is the date of the auction (which we should include, as there might be many auctions for the same domain within the same month).

**Comment by vohmar** [comment]
%{domain_name} (auction %{auction_end}) registration code
%{domain_name} (auction %{auction_end}) registreerimiskood
