### ISSUE TITLE
Admin: Option to manually mark invoices as paid

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#178]
For cases where for example payment ends up with an error even though the funds are transferred we need an option to mark manually invoices as paid.

For this operation we should require also a comment from the user why this is done manually and for the payment_order record we should also record the bank and date where the funds have arrived

**Comment by maciej-szlosarczyk** [comment]
This should not be implemented before #142. It is imperative that we have a trail of who updated the invoice manually.

**Comment by maciej-szlosarczyk** [comment]
No longer blocked, as #142 is already merged.

**Comment by vohmar** [comment]
* current solution does not have any way for admin to leave a note or comment on why is the invoice manually marked as paid
* there is no way to tell the difference whether the invoice is marked as paid manually by admin or automatically (is updated_by field in invoices table the way to tell the difference?)
* no record is created in payment_orders db table - is this intentional? It would be useful if admin is able to set where did we receive the funds

**Comment by maciej-szlosarczyk** [comment]
1. I missed that, I will add it. 
2. Yes, `updated_by` is the field that tells the difference.
3. Payment orders are for payment gateways, not auction administrators. They are not designed to be updated by a person at all. That is also why we don’t list them anywhere in the interface. A bank or credit card processor signs the data in payment orders with a private key, if we allow an administrator to freely change that data, there will be no difference between a payment order that has been tampered with by an attacker or edited by an administrator, as both have invalid cryptographic signatures. 

If we need to expose through which processor was a payment received, that is a different functionality that can be implemented without compromising the payment orders, but that is outside the scope of this ticket.
