### ISSUE TITLE
Wishlist

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#192]
Add wishlist function to auction portal where logged in users can put the domain names they are interested in and auction portal will automatically inform the user when a domain in their wishlist is put to auction

There should also be an option for the user to choose how to get notified - email and/or sms. At least one has to be selected.

Wishlist might also show the current delete date for the domain according to current registration information (date provided that current registrant decides not to renew the domain). This must be calculated in case the delete_at and force_delete_date values are empty - the formula: valid_to + expire warning period + redemption grace period

**Comment by maciej-szlosarczyk** [comment]
I am afraid there are two separate ways of going about it:

In auction, we can implement a wishlist where a user enters `example.ee` and gets notified by email or SMS if that domain ends up in auction. Auction does not know when a particular domain will expire until there is an auction associated with.

We can implement a wishlist with a countdown in registrant portal, because it does have the information about force delete dates. Technically this would be better, but at the moment registrant portal is limited only to Estonian citizens, so that limits our audience.

**Comment by vohmar** [comment]
I agree there are ways to improve this but I think the auction portal approach is good enough for starters as it gives the info necessary for this to work. We cannot be sure if anything will be actually available to apply for until it is at auction.

**Comment by vohmar** [comment]
translations:
* Whishlist - Soovidenimekiri
* You can add up to 10 domains to your wishlist. - Nimekirja saad lisada kuni 10 domeeninime
* Add domains to your wishlist - Lisa domeeninimi oma soovidenimekirja.
* in unicode format, ... - Täpitähed on olulised - päev.ee ei ole sama mis paev.ee
* Wait for notification - Oota teadet.
* Once a domain from your wishlist... - Saadame epostiga teate ning eemaldame nime nimekirjast kui domeeninimi läheb oksjonile. Võib minna väga kaua aega enne kui domeeninimi jõuab oksjonile seepärast kirjed nimekirjas ei aegu.
* New item - Lisa uus domeeninimi

errors:
* Domain name ei ole korrektne - Domeeninimi ei ole korrektne

**Comment by vohmar** [comment]
error issue on trying enter same domain name multiple times:
"Domain name has already been taken" replace with
et: Domeeninimi on juba nimekirjas
en: DOmain name is already in your whishlist

**Comment by vohmar** [comment]
mailer text in the gdocs, the last chapter

also it turns out Soovidenimekiri is actually two words - Soovide nimekiri. Please correct the spelling for the first and third translation and second error (https://github.com/internetee/auction_center/issues/192#issuecomment-494310972). Sorry for that!

**Comment by vohmar** [comment]
* shouldn't the entries be removed from wishlists once the domain name is at auction?
* please also fix the "soovide nimekiri" typo referenced in the last comment

**Comment by maciej-szlosarczyk** [comment]
I don't think removing the entry automatically is user-friendly. Sending a second notification when a domain is re-auctioned seems like a better approach in the following scenario:

User A wants domain `test.ee`, so he puts it in wishlist. `test.ee` goes to auction, but User B makes a higher offer and wins the auction. If user B does not pay or does not register the domain before the deadline, User A still probably wants it. 

The same probably applies if the domain expires next year.

**Comment by maciej-szlosarczyk** [comment]
@vohmar "soovide nimekiri" is changed, you can check again.

**Comment by vohmar** [comment]
OK, soovide nimekiri seems ok, 
Regarding not removing automatically anything from the wishlist - what if the user wins the bid for the domain in their list? Anyway, we need to once more change a translation for  the second tip "Oota teadet" new text:

et: Saadame epostiga teate, kui soovitud domeeninimi läheb oksjonile. Võib minna väga kaua aega enne kui domeeninimi jõuab oksjonile seepärast kirjed nimekirjas ei aegu.

**Comment by maciej-szlosarczyk** [comment]
Text updated.

> Regarding not removing automatically anything from the wishlist - what if the user wins the bid for the domain in their list? 

Current version does not do that. I do not think we should remove that domain from wishlist, for transparency sake. It would need to be explained really well in the UI. If a user already acquired `test.ee`, and run out of space in their wishlist, they can remove it from the same place. 

Additional angle is that we also don't check if a user has an active ban when we send the wishlist notification. You obviously still cannot submit an offer, but there's no harm in letting you know.

Both are subject to change, but I'd get it out first so people can use it, and then we can look at feedback and usage patterns to decide what should be improved.
