### ISSUE TITLE
New version of the invoice not paid email message

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#194]
New revised version of the email message informing about the fact and consequences of failing to pay for the auction invoice can be found in the automated email message document under paragraph "Oksjonil osalemise keeld (tasumata arve)", there are also messages for the second and third offense right after that.

**Comment by maciej-szlosarczyk** [comment]
The emails do not correspond with what the functionality actually does.

- First ban is for 3 months (shortest possible registration period for a domain), and one specific domain.
- Second and any consecutive ban is for all domains and it lasts as many months as is set in Settings (ban length), by default that's 100 months, AFAIR in production that's 12.
- There is no third ban, there is no account closing (what does that mean?)

**Comment by vohmar** [comment]
* first email is OK, there is no reference on the length of the ban for that particular domain name. only the policy of not being able to participate in any auctions for a year after the third offense is described.
* we need to change the offence count for the ban from any auctions. The current .ee auction policy states it takes effect after the third unpaid invoice
* the ideal solution here would be to have separate email for the second offense but that is not absolutely necessary. First priority is to make the ban happen with the third offense and have correct email for that occasion

I will move the offense count issue to a separate ticket so we can fix the texts here
Ticket for the ban count issue:
https://github.com/internetee/auction_center/issues/198

**Comment by vohmar** [comment]
text for the first warning in estonian does not match the text in the doc. 
* The second paragraph should be: "Pärast kolmandat tasumata arvet ei ole Sul võimalik järgneva aasta jooksul .ee domeenioksjonitel osaleda."
* Missing dot (.) after the overdue invoice count in the third paragraph
* subject of the email should include the domainname

text for the third offense
* missing the domain name in the first paragraph
* please remove the time part from the ban end date

**Comment by maciej-szlosarczyk** [comment]
> missing the domain name in the first paragraph

There cannot be domain name in third offense email, since there isn't one. When column bans.domain_name is empty, it means that it applies to any domain.

Also, in the document, the English text does not contain a domain name.
