### ISSUE TITLE
Banning users

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#198]
Currently the auction center bans users from participating in any auctions for a configurable period of time after the second unpaid invoice. This is in violation with .ee auction policy stating that ban from any auctions will happen after third offense.

We do not have to have separate warning email templates for the first and second offense. instead we could make the number of offenses required for the absolute ban configurable and put the offense count in the initial offense email template stating

et:
"See on teie 1./2. maksmata arve"

en:
"This is your 1st/2nd overdue invoice"

As a bonus we should also implement the period for an offense to be active. Meaning that for example after a year from any offense it expires and is not taken into account any more. But this can be solved later in separate ticket as well.

**Comment by maciej-szlosarczyk** [comment]
Changes in PR #209:

- Add new setting `ban_number_of_strikes`, at which we apply the long ban, with default value 3.
- Make bans explicitly tied to number of overdue invoices.
- Include domain name in both emails, about short and long ban, as it was missing from yesterday's update and now it's technically possible.
- Email about the long ban includes the number of unpaid invoices. It can be that a user creates bids for 4 or more domains on the same date and gets a long ban multiple times.

**Comment by vohmar** [comment]
Was able to create 5 bans for a user (ban_number_of_strikes was set on 3). Few questions:
* are the bans from before the patch taken into account?
* when is the ban count reset (the third canceled invoice produced a ban email that said this is violation nr 1)?

**Comment by maciej-szlosarczyk** [comment]
Bans from before the patch are not taken into account. With this change, bans are created solely on basis of number of cancelled invoices. Manual bans also do not count towards that.

There is no reset, ever. Once you have reached the `ban_number_of_strikes` threshold, each subsequent violation results in a ban for 12 months. I do not think implementing any expiration is advised for people who have not paid 3 or more invoices.

Given that all the testing was done on the basis of 3 domains, would it be possible that emails arrived out of order that emails arrived out of order?

In any case, I'll add a relation between the ban and the actually unpaid invoice, it should make this a bit clearer to understand.

**Comment by maciej-szlosarczyk** [comment]
@vohmar You can redeploy and retest, now in the admin interface, each automatic ban should have a link to the invoice that triggered it.
