### ISSUE TITLE
Error is returned if a user with warning ban tries to make a bet to another domain 

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#201]
User with active warning ban for a specific domain due to overdue invoice gets error 500 on trying to make a bid for another auction

![image](https://user-images.githubusercontent.com/7734747/55477565-143e1300-5622-11e9-8733-8d9b92d2ac8b.png)

**Comment by vohmar** [comment]
it appears that the bid it self went through and was registered

**Comment by maciej-szlosarczyk** [comment]
I don't see anything in Errbit, but it seems in the logs there's an error related to a permissions query. I'll look into it.

**Comment by vohmar** [comment]
Same error for users with any type of ban is returned when trying to access offers page
