### ISSUE TITLE
automatic login from email

### ISSUE THREAD

**Issue by rieussec** [internetee/auction_center#225]
It would be nice if the links in emails allow an automatic login to the user's account. Currently you must enter your login / password to show your page. Thank you !

**Comment by maciej-szlosarczyk** [comment]
Outside of email address confirmation, this a either a security risk or complex feature. 

Emails are only encrypted in transit, so anyone who gets access to a user's email account or one specific email, automatically gets access to their account in auction system. The links would need to time out after a certain duration and be encrypted, and also stored in auction database to make sure that they cannot be reused.

**Comment by vohmar** [comment]
@rieussec hi, we are taking a look into this issue and would like to get clearer understanding what did you have in mind with this request. On password reset is not an issue here, email update is done already being logged in so no obvious issue there as well. But in case of other automatic emails that are initiated by the server and sent to user on some specific event should not have this for security reasons as @maciej-szlosarczyk maciej also mentioned. So to be clear and not to miss a good idea, I would like to ask you to explain in more detail what is that you are requesting here.

**Comment by rieussec** [comment]
Hi as @maciej-szlosarczyk said maybe this feature is a little bit complex for a small benefits. This feature could be nice when you win an auction and you received the email, it could be great to allow user to go directly to its invoice or billing preferences to save time. But it's a security risk to compromise the account, I agree. Thanks you again for your great job.
