### ISSUE TITLE
Hide references to domain names from ban messages if these are not being auctioned

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#229]
Current soft ban message lists the domain names that user is banned from participating. The ban should last until the specific domain is out of auction cycle ie no bids were made and domain is released or an auction winner has registered it.

If this happens, the ban is not relevant any more and hence the ui should not return that domain name. So the auction center should remove the domain name from the presented list if the domain is not at auction. If the removed domain name is the last the whole ban message should be removed.

Referencing: https://github.com/internetee/auction_center/issues/202

**Comment by vohmar** [comment]
The count of active bans should always be visible to the user in the UI.

**Comment by vohmar** [comment]
"soft" ban message is in two parts. Part 1 notifies user about active bans regarding domains currently in auction process (in auction, waiting for payment or registration). Part 2 is about number of active soft bans out of 3 allowed (shown if user has 1 or 2 bans according to current .ee regulations - configurable in admin - ban_number_of_strikes):
current  soft ban message is OK for Part1
Part2: (possibly add a link to auction regulations pt 7 - word violations/rikkumisi could be made as a link)

en: Number of current violations (https://www.internet.ee/domains/auction-environment-user-agreement#7-validity-and-termination-of-the-user-agreement): x of ban_number_of_strikes

et: Oksjoni reeglite rikkumisi (https://www.internet.ee/domeenid/domeenide-oksjonikeskkonna-kasutajatingimused#kasutajalepingu-kestus-ja-lopetamine): x 'ban_number_of_strikes'st

current hard ban message is OK

**Comment by vohmar** [comment]
The message with the count of violations needs some font fiddling its hardly readable on the red background - especially the violations link (where should the link take the user? it seems to point back to current page at the moment on staging?)

![image](https://user-images.githubusercontent.com/7734747/69351930-b6c80680-0c84-11ea-9d52-275f31962a83.png)

**Comment by yulgolem** [comment]
The link is leading to URL set in Settings/violations_count_regulations_link.
I'll try to make it more readable.
