### ISSUE TITLE
Users are always directed to english banklink payment form

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#238]
Feedback from a user pointed out that we redirect all users to english banklink payment forms regardless of the user language setting in auction center.

The language is currently hardcoded. The user profile language setting should be used in redirect url.

We user language in ISO 639 2 letter code format in the db

But at least LHV requires three letter code in the url. From the documentation it is unclear what standard is followed iso 3166 alpha 3 for three letter country codes or iso 639-2 for 2 letter language codes or if any of the standards is followed at all and it is pure coincidence the codes match at the moment.

**Comment by maciej-szlosarczyk** [comment]
Implementation in #241 directs users with Estonian locale to Estonian version of bank link and every one else to English. Can be improved when we support more languages.
