### ISSUE TITLE
VAT code in billing profile has unique constraint

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#26]
System does not allow adding multiple billing profiles with the same vat code in the system. While this is OK for a single user it is not for the whole system as every organisatsion can have multiple representatives. 

At the same time adding a billing profile must not give access to any of the invoices assigned to that company (bids are done by a unique users and only that user has access to the billing and authorisation code related to the winning bid)

Also error handlung is missing for adding multiple profiles with the same vat code for the same user - error 500 is returned.

**Comment by vohmar** [comment]
It is not possible to add new profile with already existing vat to a user, but it is possible to update already existing profile to any vat.

**Comment by maciej-szlosarczyk** [comment]
It seems like it's related to the old data for one specific user profile. I wasn't able to reproduce it outside of that one.

Additionally, I fixed #35 and removed the obsolete `legal_entity` checkbox.
