### ISSUE TITLE
Option to send more registration reminders

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#266]
As we still have many paid but not registered auction domains we would like to intensify the number of reminders sent to auction winners. Currently we have an option to send one reminder configurable days before registration deadline.

Add additional option to send the reminder every day after the first reminder until the domain is registered or deadline is reached.

**Comment by yulgolem** [comment]
I'll make option to send more registration reminders enabled/disabled via customization.yml, if it's ok?

**Comment by vohmar** [comment]
I am a bit confused. I see two new settings:
* remind_on_domain_registration_everyday
* domain_registration_reminder_day

but there is already pre existing setting called
* domain_registration_reminder

what is the difference in the new and pre-existing registration reminder setting? Descriptions are identical.

**Comment by yulgolem** [comment]
If `remind_on_domain_registration_everyday` is set to `true`, then the reminders are set to all results where registration due date is up to `domain_registration_reminder_day` ahead.

I might get rid of it and use one single `domain_registration_reminder` in no time.

**Comment by yulgolem** [comment]
Modified PR, set all everyday reminders to single `domain_registration_daily_reminder` setting - integer, zero or more.
If zero, then reminders are only sent once, if more, then reminders are sent once as usual, then from the `domain_registration_daily_reminder`.days until `registration_due_date`.

**Comment by vohmar** [comment]
* reminder is not sent on the last day. Ie registration_due_date value is 2020-01-22 (today) last reminder sent a day ago, but the DomainRegistrationReminderJob is not active in the ui
![image](https://user-images.githubusercontent.com/7734747/72908016-8e6c8f00-3d3d-11ea-8f3f-74c2b8a64a36.png)

* the day counter in the reminder email is constant (5 päeva / 5 days), but should be calculated from todays date and registration_due_date
  * would it be possible to use set strings here. So if the calculation results 
    * anything higher than 1 then the value would be "Teil on jäänud X päeva..."/ "You have X days..." (replace X with the value from the calculation)
    * equals 1 then "Teil on jäänud 1 päev..." / "You have 1 day..."
    * equals 0 then "Täna on viimane päev..." / "Today is the last day..."
* in estonian reminder email the domain name in the email body, 2nd sentance is not replaced with real value - it is <timo-nons3>

**Comment by vohmar** [comment]
* recurring emails sent too soon. Settings domain_registration_reminder: 6, domain_registration_daily_reminder: 3. Reminder email was sent 5 and also 4 days before deadline even though the email was sent the day before and the fact was saved in registration_reminder_sent_at
* in estonian reminder email the domain name in the email body, 2nd sentence is still not replaced with real value
![image](https://user-images.githubusercontent.com/7734747/72996543-9858c580-3e03-11ea-8d34-6c02c247d7c8.png)
* in the new english reminder letter for the last day the second sentance says "You have last day..." while it should say "Today is the last day..."

**Comment by yulgolem** [comment]
Fixed estonian second sentence:
![image](https://user-images.githubusercontent.com/7688888/73007268-15993000-3e2e-11ea-9bbe-16da2d258113.png)

Fixed english last day reminder:
![image](https://user-images.githubusercontent.com/7688888/73007313-2b0e5a00-3e2e-11ea-85dc-7af860952dd2.png)

Fixed dates. Now letter should be sent either at domain_registration_reminder days, or from domain_registration_daily_reminder days until the registration_due_date.

Added tests for job not to run between domain_registration_reminder days and domain_registration_daily_reminder days, as well as after registration_due_date.

**Comment by vohmar** [comment]
* now the initial / the first reminder is sent too soon - seems that it is sent right after the payment is made disregarding the domain_registration_reminder setting value.  Example: domain_registration_reminder = 6, and auction winner received reminder saying "...You have 8 days to contact an accredited...". Day count is correct in this instance it is 8 days til registration deadline at the moment of running the DomainRegistrationReminderJob

**Comment by yulgolem** [comment]
> * now the initial / the first reminder is sent too soon - seems that it is sent right after the payment is made disregarding the domain_registration_reminder setting value.  

Fixed premature reminder sending, added test.
