### ISSUE TITLE
country selection should be dropdown

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#28]
Country selection in any form should be dropdown 

/billing_profiles/new
/billing_profiles/1/edit

**Comment by vohmar** [comment]
* Create new billing profile: set country to anything - the result after saving is always Estonia.
* Update billing profile works - successfully able to change the country to something other than Estonia.
* Update user profile - set country to anything the result will remain unchanged (even though update successful message is returned) - same result when admin tries to update country of any user.

**Comment by maciej-szlosarczyk** [comment]
Scenarios 1 and 3 were a result of the form having wrongly set default. Now it should be better.

Additionally, I made the default country configurable by administrator, it is a setting similar to minimum price or currency.

**Comment by vohmar** [comment]
problem 3 is still there. The initial value is retained - does not look like html issue, the value is not update in this case

**Comment by maciej-szlosarczyk** [comment]
Fixed by allowing to change the identity code for an existing user as well. The issue was that update to user's country code was not allowed because of the dependency identity code holds on it. Now you can change both, since it is a standard procedure when people move from country to country.
