### ISSUE TITLE
Admin: Add turn count to auction list

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#289]
Add counter of the number of rounds the same domain has been cycling through auction process without being released or registered

statuses can be used to determine the fate of an auction
no bids - domain no bids were made and domain was released - cycle ended
domain_registered - domain was registered - cycle ended
payment_not_received - bid was made, but the invoice was not paid - new round
domain_not_registered - bid was made, invoice was paid, but domain was not registered - new round

other statuses indicate ongoing auction process

(Martin has script to calculate this)

This is needed so we could track and spot if some domains are circling around for too long indicating possible abuse.

**Comment by vohmar** [comment]
matrin's query: select domain_name, count(domain_name) from auctions group by domain_name having count(domain_name) > 1 order by count, domain_name;

it must be modified a bit as this one does not take into account the possibility that the domain name was registered in between (that should reset the count on next auction).

**Comment by yulgolem** [comment]
After deploy run `rake data_migrations:count_auction_turns `

**Comment by vohmar** [comment]
fixed by #450
