### ISSUE TITLE
Further imporve readability of domain names

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#294]
related to https://github.com/internetee/auction_center/issues/251

enforcing monospace font type helped in differentiating some characters like g, 9, o, 0, but we currently request systems default monospace font to be used and that differs between different OSs resulting in different results that most painfully reveal in differencing 1 and l.

For this we might need to use font that is not currently included in the design book as those do not seem to resolve the issue too well. One of the better options I have found is Deja Vu monospace

https://dejavu-fonts.github.io/

**Comment by virtualfeline** [comment]
Deja Vu looks really good on the 1-I-l front, not much improvement to the g and 9 issue though, IMO

**Comment by vohmar** [comment]
![image](https://user-images.githubusercontent.com/7734747/60182575-3d3f0000-982d-11e9-9f57-f5468cc4e810.png)
![image](https://user-images.githubusercontent.com/7734747/60182617-5051d000-982d-11e9-964e-e8d454699a86.png)

**Comment by virtualfeline** [comment]
Yes, as we can see this looks like the 'g' we have now, more or less. Whereas Consolas uses a looptail g that is totally impossible to confuse with 9. On the other hand, the lowercase l and 1 are a lot more similar in Consolas than they are in Deja.  Since the latter is the greater problem we should probably choose Deja over Consolas.

**Comment by maciej-szlosarczyk** [comment]
I guess changing the font color for numbers should also contribute to mitigating this problem, I'll try that too.

**Comment by maciej-szlosarczyk** [comment]
![Screenshot 2019-07-03 at 11 52 56](https://user-images.githubusercontent.com/2331765/60578017-277b8e80-9d89-11e9-93a1-294001a7ad02.png)
![Screenshot 2019-07-03 at 11 53 01](https://user-images.githubusercontent.com/2331765/60578018-28142500-9d89-11e9-849e-e19e277d3c1f.png)

This should improve the situation additionally, the numbers are a different color from our palette.
