### ISSUE TITLE
Possible to delete billing profile with active offers

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#313]
User is able to delete the billing profile that they just made an offer with. As a result auction system is not able to generate invoice in case the offer is the best. It should not be possible to delete billing profile that has active offer associated to it - user should first change the profile in the offer.

Also if user tries to delete their profile associated with an invoice it fails with no message. There should be an error message stating the reason why operation failed.

**Comment by karlerikounapuu** [comment]
> Also if user tries to delete their profile associated with an invoice it fails with no message.
> There should be an error message stating the reason why operation failed.

@vohmar 500 internal error is returned with operation, hence why user doesn't get any output at all. Invoice belongs to BillingProfile by current design. You can't delete parent.

Two possibilities with this one:

1) simply tell an user you can't destroy billing profile which is already associated with Invoice
2) use logical deleting, eg. nullify user_id for BillingProfile. User won't see BillingProfile under his account anymore, but in reality it simply floats around with no user attached and invoices are not affected.

Which one should we proceed with?

**Comment by vohmar** [comment]
as orphaned objects are not desirable the 2nd option is kind of out. At the same time I see a design issue here - it seems equally bad to block removing profiles that have invoices associated with. It seems to me that invoice should have a relation with the user instead of the profile. Invoice gets the recipient data from the profile but should save the data as it was at the time of invoice creation or last update before invoice was marked as paid and locked (profile could be an optional tag/label with the invoice to enable filtering out invoices per profile).
