### ISSUE TITLE
Admin: order users from newest to oldest

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#316]
There is no specified sort order for users list at the moment - the list is displayed in the order the result comes from db that is generally ordered ascending by id meaning that the first users created in the system are always the first in the list.

**Comment by vohmar** [comment]
can you extend this solution to other admin views as well:
* auctions (alternatively starts at desc could be used)
* results (alternatively finished at desc could be used)
* billing profiles
* bans (alternatively valid from desc could be used)
* invoices (alternatively due date desc could be used)

**Comment by karlerikounapuu** [comment]
> can you extend this solution to other admin views as well:
> 
> * auctions (alternatively starts at desc could be used)
> * results (alternatively finished at desc could be used)
> * billing profiles
> * bans (alternatively valid from desc could be used)
> * invoices (alternatively due date desc could be used)

Sure can do!
