### ISSUE TITLE
Add health check status page

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#343]
It's desired to have application based health status check functionality to make it easier for monitoring systems to get an overview of what works and what does not. If applicable this should be implemented to all our systems in unified manner, but let's start here

gem that may be of help here:
https://github.com/ianheggie/health_check

gitlab example:
https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html

**Comment by yulgolem** [comment]
The health_check gem looks old/unmaintained, latest commit on 13 Mar 2018 and there is no Rails 6 support yet.
In master we've got this gem installed - https://github.com/sportngin/okcomputer
It comes with auth (ENV['HEALTHCHECK_USER']/ ENV['HEALTHCHECK_PASSWORD']) and provides text and json as well:
![image](https://user-images.githubusercontent.com/7688888/67859340-3575cc00-fb3d-11e9-8fc7-dd88a4af591a.png)
Maybe this will be enough?

**Comment by yulgolem** [comment]
We should check all the vital parts of auction process - portal is running (incl public auction list api), db is ok, registry api is accessible and registry is responsive, email works, sms service is ok, payment provider (EveryPay) works, tara ie authentication service is responsive.
So we'll need some custom checks on this components.

**Comment by vohmar** [comment]
sms service monitoring: they proposed to query messentes own status api https://status.messente.com/api/v1/components/1 (doc: https://docs.cachethq.io/reference#get-a-component). Not sure this is enough - depending if the status service is on the same machine as sms service... Messente status page: https://status.messente.com/

**Comment by yulgolem** [comment]
Fine, their status API is enough. I'll add it.

**Comment by vohmar** [comment]
TARA (auth service) monitoring: there is no specific solution for puposes like ours, but they proposed to query for TARA metadata - if the response is HTTP 200 then the service is up and running.

**Comment by yulgolem** [comment]
> TARA (auth service) monitoring: there is no specific solution for puposes like ours, but they proposed to query for TARA metadata - if the response is HTTP 200 then the service is up and running.

Yep, I found one of their endpoints answering 200 already, I'll just check it then.

**Comment by vohmar** [comment]
Discussed email health check with ops. I think it is enough to make just port connect to smtp server and quit. This shows that smtp server is there and accessible. I think that it is not necessary to try to send any dummy emails. Another option would be to send helo request to smtp and quit - same idea.

**Comment by yulgolem** [comment]
> Discussed email health check with ops. I think it is enough to make just port connect to smtp server and quit. This shows that smtp server is there and accessible. I think that it is not necessary to try to send any dummy emails. Another option would be to send helo request to smtp and quit - same idea.

Fine by me, I'll check it then.

**Comment by vohmar** [comment]
It turns out there is not good way of checking payment provider availability, but this will be solved in EveryPay APIv3 that will be released soon. We will be notified as soon as this happens and presented with relevant documentation. 

Alternatively we can monitor the actual payment operations and deduce from that whether payments function properly. Of course this will alert/'turn red' only after a user has stumbled on the problem.

But its also ok to leave EveryPay health check out until APIv3 is available,

**Comment by yulgolem** [comment]
Well, if we use some kind of metrics check like Prometheus, we might monitor payment system status in runtime, but here we would like to have some kind of endpoint to check as "per-use" basis.
So my proposal is to pause payment system healthcheck either until we'll use metrics based monitoring or until APIv3 comes out.

**Comment by vohmar** [comment]
done - no payment system health check in this one.
