### ISSUE TITLE
Wishlist: multiple errors on failed item entry attempt

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#358]
If user tries to add an item to the wishlist that is already in their wishlist error "Domeeninimi is already in your wishlist" error is returned. But sometimes there are more than one such messages returned

![image](https://user-images.githubusercontent.com/7734747/66471971-f354ef80-ea94-11e9-8590-f3fa63bea4de.png)

if user goes straight to wishlist view after login only one error message is returned, but if he/she has clicked around between different views the number of error messages is raised.

**Comment by artur-beljajev** [comment]
https://prnt.sc/pgv0u6

**Comment by artur-beljajev** [comment]
> But sometimes there are more than one such messages returned

The exact steps to reproduce are:

1. Type the domain that is not yet on the list and ENTER key
2. Wait until you see "Created successfully." message
3. Repeat step 1
