### ISSUE TITLE
Consider Settings refactoring

### ISSUE THREAD

**Issue by yulgolem** [internetee/auction_center#382]
As Karl mentioned before, we're already have two issues (#372 and #356 ) that shows us that the current structure of the Setting object does not suit us well.
We cannot change type of setting stored if we need some kind of serialization, etc, etc.

So - why don't we create some kind of custom settings object not in Entity-attribute-value paradigm, but with classic relation DB approach, where one column will be equal one or more settings (maybe via store_accessor, stored in json instead of text... but it's unnecessary details atm), and one table entry will be equal the whole settings set for application?

We might leave Setting class as a settings wrapper for some kind of backward compatibility as well.

@karlerikounapuu , @artur-beljajev your thoughts?

**Comment by karlerikounapuu** [comment]
If I'm not mistaken, I think we already have some experimental new logic in one of opened PR's (#410), which should partially mitigate an issue with custom Setting value validations. I've given it a go by approving it, so I guess it gets merged into master (yay) pretty soon.

However, another issue which is going to appear very-very soon is that Setting class is getting too massive, eg too many methods.  As soon as it exceeds 20 methods, we're back at failing CC style tests again.

What if we introduce some generic methods to avoid it? For example, `get_string_value(code:)`, `get_bool_value(code:)` and so on? This way we could avoid trashing Setting class with pretty much identical functions that are being used at the moment (self.setting_name and so on)

**Comment by yulgolem** [comment]
Agreed.
And because we are to store some entities we don't know count/format yet, we should think about storing them in some manner so neither Rails code conventions on methods count limitations, nor DB should not limit us.
Maybe some king of store_accessor and methods delegation will do the trick?
