### ISSUE TITLE
Prevent user from deleting account if unpaid invoices issued

### ISSUE THREAD

**Issue by karlerikounapuu** [internetee/auction_center#385]
At the moment user can destroy their account without any obligations. Destroying user should be prevented if they have won an auction and (unpaid) invoice issued.

**Comment by vohmar** [comment]
we run full history policy in our registry so just incase I am stressing that delete/destroy in our context must mean technically archivation - moving object/records from active tables to archive tables (or deleting from active records if archive records are already there)

**Comment by yulgolem** [comment]
So in general this issue has two parts:

- [ ]  Make a safe-delete options for some models. Acts_as_paranoid maybe?

- [ ]  Prevent deleting of User model if there is any issued invoices linked to it.

**Comment by yulgolem** [comment]
Closed old PR, will create new with restriction to delete if unpaid invoices present.

**Comment by vohmar** [comment]
fixed by #461
