### ISSUE TITLE
Daily auction email: Ban denies access to profile edit page

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#428]
Any type of ban - "soft" (related to one single domain name) or "hard" (participation in any auction is denied) stops access to profile edit page. This is a problem with soft bans as profile edit page now has an option to enable or disable receiving daily auction lists on email.

we need to either move the daily auction email enabling option out of the profile edit view to profile view or enable access to profile edit view but allow only changing daily email option.

As a bonus also consider automatically disabling daily email option on hard ban.

Related to #355

**Comment by karlerikounapuu** [comment]
@vohmar 

In my opinion, most UX-centric approach would be to modify current "order auction list" button on main page, which should POST request to trigger daily_auction_list boolean.

When user is subscribed, it could show button like this instead:
![image](https://user-images.githubusercontent.com/9388771/69610829-424ee800-1035-11ea-885c-74f54730a86a.png)

We can still keep "order auction list" boolean in user edit view this way and banned users could still get chance to opt in/opt-out from subscriptions.

What do you think?

**Comment by yulgolem** [comment]
Looks good for me.
But I need texts for unsubscribing procedure.
