### ISSUE TITLE
Banklink: accept automatic bank notifications on successful and unsuccessful payments 

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#482]
It seems that all three of our currently supported e-banks notify merchants on the result of payments ewgardless of user not clicking on back to merchant button at the end of process.

This is done with responses with VK_AUTO = Y element. We should implement this feature

User story:
Auction winner wants to pay for the invoice. Select bank link as a payment method. Pays the invoice successfully and then closes the window (neglecting to press the back to merchang button at the end of the process). Auction env accepts the automatically generated response from the bank and marks the invoice as paid.

**Comment by karlerikounapuu** [comment]
This issue is not relevant. PaymentOrder does not care about VK_AUTO key. Only difference between VK_AUTO=1 and VK_AUTO=0 is how request is sent from bank end, ie GET or POST. PUT, POST, and GET are all being handles with current design.
