### ISSUE TITLE
Phone nr uniqueness not enforced

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#550]
Auction env allows reusing the same phonenr for multiple users and we have users that are already taking advantage of this by participating not paying and then creating new user with the same nr and new email address.

Correct approach here should be to allow confirming each nr only once. So to reuse a nr previous one should be unconfirmed by administrator / in the database

**Comment by yulgolem** [comment]
Unless user.provider == TARA_PROVIDER:
1) user phone number must be confirmed. 
2) Confirmed phone number must be unique.

User with unconfirmed phone number might log in, but should be warned on phone confirmation necessity (like he was banned, but on yellow background). Without confirmed phone number user cannot make any offers.

**Comment by yulgolem** [comment]
If this phone number was already confirmed, we are declining to save it in user via validation and declining to confirm it in the phone_confirmations_controller.rb .

**Comment by vohmar** [comment]
Comments from testing:
1. Error message in attempt to create new user:
1.1. en: Mobile phone Phone number you've entered is already confirmed by somebody else. Please, use another phone number
It would be better if it was "Mobile phone: Phone number you've entered is already in use. Please, enter another phone number.
or just "Mobile phone number you've entered is already in use. Please, enter another phone number." But then it's the question how would it be looking in the banner message.
1.2. et: Mobiil Sisestatud telefoninumber on juba kasutuses. Palun sisestage teine number
similarly to en message
Mobiil: Telefoninumber on juba kasutuses. Palun sisestage teine number. 
or 
Mobiiltelefoninumber on juba kasutuses. Palun sisestage teine number.
PS: in case of using the colon approach the email error message needs same treatment as well to be in line

2. registration form locks up when the mobile nr error is returned - registration button is inactive

3. if mobile nr is confirmed in multiple instances, the one confirmed later? has the "nr in use" warning and gets "You are not authorized to access this page." error when trying to make a bid. Maybe we should just delete the mobile_phone_confirmed_at value for all other instances of the phone nr except the earliest confirmed one? This would avoid the confusion that in profile phone nr is marked as confirmed. and stop user from making the bid at earlier stage.

**Comment by yulgolem** [comment]
1) en/et error messages fixed.

**Comment by vohmar** [comment]
inactive button issue: https://github.com/internetee/auction_center/issues/555
