### ISSUE TITLE
Log user registration details

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#559]
User requests proof that they have agreed to user agreement / user contract. For this we need to log that user indeed selected the agree checkbox. Basically we should be able to look for all the values of all the form fields on the registration.

**Comment by yulgolem** [comment]
Actually we got this in the history, model Audit::User stores all the user changes.
Should we create something like user's history where user can see all the changes?

**Comment by yulgolem** [comment]
Yep, we've got changes in the Auction::User ('auction.user' in the DB) in old_value/new_value fields.
The field in question is `terms_and_conditions_accepted_at`.

**Comment by vohmar** [comment]
No development needed. Thank you!
