### ISSUE TITLE
User cannot make a bid without creating billing profile first

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#59]
if a new user tries to make a bid with no billing profiles an error is returned. As all defined users are private persons and nationality is one of the mandatory parameters upon creating the user there is no need to require billing profile unless the user wants the invoice in the name of a company.

Also as discussed the billing profile is only related to invoicing and thus does not come into play before the user's bid has actually won. So the user should be able to set the billing data on the invoice and no such choice needs to be made on making the bid.

**Comment by vohmar** [comment]
the default billing profile is not created and new user still has to create billing profile before being able to make a bid. It is ok if we automatically create a billing profile named same as the user's name and use this as default profile on making a bid

![image](https://user-images.githubusercontent.com/7734747/53565617-9ab68f00-3b62-11e9-8699-73e9e2d80095.png)

**Comment by maciej-szlosarczyk** [comment]
I haven't worked on this yet, so it is expected that nothing has changed.
