### ISSUE TITLE
Option for redeeming viloations and lifting bans

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#590]
New .ee auction regulations took force on 1st of January 2021 enabling auction users to redeem their violations or lift bans by settling an overdue invoice. 

New addition to the ban and violation count messages in the auction portal:

et: Tulenevalt Kasutajalepingu punktist 7.3.3. saab Teenuse kasutaja oksjonikeskkonna teenuseid kasutada, kui maksmata arveid on vähem kui kolm.
en: According to cluase 7.3.3 of the .ee Auction Environment User Agreement a user can use the service of the environment if there are less than three unpaid invoices under their user account.

Also we need to add an option to pay overdue invoice together with information that paying overdue invoice will redeem the violation but will not grant the reservation/right to register the domain the invoice was issued for. The option could be added similarly to how option to pay valid invoices is provided - pay all overdue invoices in my invoices view or pay specific one in the invoice view. The option must be separate from paying valid invoices and must be accompanied by message - above the payment buttons

et: Tühistatud arve tasumine eemaldab vastava arvega seotud rikkumise, kuid ei anna vastava domeeni registreerimiseks eelisõigust.
en: Paying for cancelled invoice will redeem the violation but will not grant priority right to register that domain.

![image](https://user-images.githubusercontent.com/7734747/106468856-2485da00-64a7-11eb-998f-1ec0fffa50ec.png)

**Comment by yulgolem** [comment]
Merged PR is a fix for Tara test/update for Airbrake gem, the redeeming feature isn't ready yet.
