### ISSUE TITLE
Submitting domain offers

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/auction_center#6]
Allow to:

- [x] Submit an offer for a domain. The offer should be in Euros and should exclude the VAT tax. Minimum amount to be determined.
- [x] Updating an offer for a domain. A user can make the offer smaller or bigger.
- [x] Removing an offer for a domain.

**Comment by vohmar** [comment]
minor issue: there is a tooltip in case of invalid valu in price bid that presumes only full values allowed. Ie if i enter value 4,999 the tip sasys that this is invalid and closest valid values are 4 and 5. In this case even 4 is not valid as the minimum amount is set to 5. So in case of 5,981 the nearest valid values should be 5,98 and 5,99. But I am not too sure giving feedback this specific is worth the effort so tip "only two decimal places allowed" would be sufficient.

**Comment by maciej-szlosarczyk** [comment]
Hey @vohmar, #45 is the fix for this issue. The tooltip wording comes from your browser, so the wording is outside of our control.
