### ISSUE TITLE
Payment link to auction winning, payment reminder and overdue email messages

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#606]
Add a PSD2 payment links to auction winning, invoice payment reminder and overdue/violation email notifications

https://support.every-pay.com/et/merchant-support/linkpay-makselink/
https://support.every-pay.com/et/search/linkpay/

**Comment by yulgolem** [comment]
Task has two parts:
1) Setup Linkpay url generation
1) Setup callback endpoint to automatically set payment_orders paid via Linkpay in `paid` status.
