### ISSUE TITLE
Registration password is available prior to paying the invoice

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#61]
The registration password is available once the user has won the bidding (regardless if the invoice has been paid or not)

![image](https://user-images.githubusercontent.com/7734747/51112575-c88c8200-1807-11e9-9d01-fe2c28aff278.png)

**Comment by maciej-szlosarczyk** [comment]
This should be fixed with registry integration (#74)

**Comment by vohmar** [comment]
fixed
