### ISSUE TITLE
Async job processing with delayed_job

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [internetee/auction_center#8]
Use delayed_job for processing tasks that require background processing:

- Sending emails to winners of auctions
- Fetching the list of domains to auction
- Sending auction results to registry

---
The reason why we should go with `delayed_job`, and not `sidekiq` is that the latter does only support redis as backend, thus adding one more infrastructure element that needs to be managed and updated.

**Comment by artur-beljajev** [comment]
I agree with that argument against introducing Redis.

At the same time, I suspect "sidekiq" with Redis runs way faster and efficiently, than `postgresql`.

**Comment by maciej-szlosarczyk** [comment]
> At the same time, I suspect sidekiq with Redis runs way faster and efficiently, than Postgresql.

I'd benchmark it first if I were to make an assertion like that. However, [as Sidekiq author points out](https://github.com/mperham/sidekiq/wiki/FAQ), `delayed_job` scalability becomes a problem at around 100 000 jobs per day. We will have about 2000 (and that is *very* generous estimate).

> Also, I am not sure if background processes data is relational.

Can you elaborate? I am afraid that I don't understand.

> I wonder if there is a way to start with Postgresql (=delayed_job), and then switch to sidekiq, once we realize it doesn't fulfill our needs anymore.

Sure is, both work against ActiveJob. As long as jobs are thread-safe, the eventual switch is possible. Though I doubt it will ever be necessary.

**Comment by artur-beljajev** [comment]
Well, indeed, 2000 per day does not make any difference. Let's try `delayed_job`!

**Comment by maciej-szlosarczyk** [comment]
> I mean that the data about every background job we store is kinda queue, we don't need all the features of relational database for it.

Sure, but we already have a relational database in place at no cost, even if there are not too many relational features used.
