### ISSUE TITLE
English: deposit collection and management on high value domains

### ISSUE THREAD

**Issue by vohmar** [internetee/auction_center#940]
add option to set deposit requirement for English auctions.
Once enabled, it is possible to participate in the auction only if the deposit payment is done
Required deposit amount needs to be configurable as well.

If user want to participate in the auction with deposit requirement 
1. logged in user presses the pay the deposit button and makes the payment using Everypay APIv4 payment method
2. An invoice is generated for the deposit sum
3. once the payment is successful user can start bidding
4. ??? once the auction is finished and winner in place - the deposit is returned to loosing participants
5. an invoice is generated for the winner for the sum bidded. Sum to be paid on the invoice is deducted by the deposited sum (ie depsit 500€, winning bid 1000€, the invoice is generated for 1000€+vat, deposited sum is also listed and the total sum to be paid is for 500€ (1000-500)

**Comment by OlegPhenomenon** [comment]
Implemented in #900
